variable "instance_type" {
    type = string
    default = "t3.micro"
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}